#!/usr/bin/env bash

if [ -z "$1" ] || [ "$1" = '-h' ] || [ "$1" = '--help' ]; then
    fmt <<EOF

Usage: jutge-run <command> [args...]

Execute commands in a container using one of the Jutge images.

By default, it maps the current directory as /home/worker in the 
container, and runs "<command> args...".

However, if <command> is "jutge-submit", the current directory is NOT
mounted and all communication is expected to be through pipes.

EOF
    exit
fi

# Find out the version of the Docker image to use
for candidate in server full lite; do
    docker image inspect jutge-org/$candidate > /dev/null 2>&1
    if [ $? -eq 0 ]; then
        version="$candidate"
        break
    fi
done
if [ -z "$version" ]; then
    version='jutge.org-lite'
fi

# Determine running options:
# - jail: no network, limited memory and CPU (for "jutge-submit")
# - term: interactive terminal
# - volume: mount current directory
# - user: run as the current user
#
if [ $1 == 'jutge-submit' ]; then
    jail="--network none --memory=1g --cpus=1"
else
    volume="-v $(pwd):/home/worker"
    if [ -t 1 ]; then # check if stdout is a TTY
        term="-t"
    fi
    # ???
    if [ $1 != 'bash' ]; then
        user="-u $(id -u):$(id -g)"
    fi
fi

# Run it
docker run --rm -i $term $jail $user $volume jutge-org/$version $@